apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gallasmur/mi-aplicacion-flask-kubectlbranch:latest
        command: ["/bin/bash", "-c", "./manage.sh && python run.py"]
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: "postgresql://user:password@db-service/dbname"
        

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
