version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: /bin/bash -c "./manage.sh && python run.py"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: postgresql://user:password@db/dbname
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
